### ISSUE TITLE
Suggestion: Add install_requires= in setup.py setup() call

### ISSUE THREAD

**Issue by texadactyl** [mirca/transit-periodogram#9]
I was following the procedure on http://lightkurve.keplerscience.org/tutorials/2.02-recover-a-planet.html when I ran into a minor issue.  For scientists who do much less software development or primarily develop in other languages, this might be confusing.

If you add an `install_requires=` line in the setup.py's setup() call, then when folks install from this github site, they should get those modules installed automatically (if not already installed) without failing the first time.  

For example, I did not have the **Cython** package installed yet and transit-periodogram is dependent on it.

No issues once installed.

**Comment by mirca** [comment]
@texadactyl This repo was actually experimental, if you need to use this functionality I recommend you to look at https://github.com/dfm/bls.py. Thanks for pointing this issue though! The tutorial you mentioned is going to be fixed soon!
